name: movie-emotions-analyzer          
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12                       
  - numpy=1.26.4                             
  - pandas                             
  - requests                              
  - ffmpeg-python
  - opencv                            
  - pip                                
  - pip:
    - tensorboard==2.17.0
    - ml-dtypes==0.4.0
    - deepface==0.0.91